<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Advertisement;
use App\Models\Category;

class AdvertisementSeeder extends Seeder
{
    public function run()
    {
        $categories = Category::all();

        foreach ($categories as $category) {
            for ($i = 1; $i <= 5; $i++) {
                Advertisement::create([
                    'title' => 'Dummy no photo Ad',
                    'price' => random_int(1,10000),
                    'category_id' => $category->id,
                    'description' => 'This ad has been generated by seeder',
                    'seller_id' => 81,
                ]);
            }

            $category->update([
                'amount_of_listings' => $category->advertisements()->count(),
            ]);
        }
    }
}


